@echo off
setlocal
rem ============================================================
rem Quartermaster dxgi.dll Proxy Build Script
rem
rem Usage:
rem   build.bat            - dev build (verbose logs + diagnostic code)
rem   build.bat release    - production build (info-only logs, no diag)
rem
rem The release switch defines QM_BUILD_PRODUCTION which trims:
rem  - per-hit debug/trace log lines (only ERROR/WARN/INFO remain)
rem  - all #if QM_DIAG read-only inspectors and class-byte dumps
rem ============================================================

set SCRIPT_DIR=%~dp0
pushd "%SCRIPT_DIR%"

rem Setup VS 2022 Community x64 environment
call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat" >nul
if errorlevel 1 (
    echo [build] vcvars64.bat failed.
    popd
    exit /b 1
)

rem Clean previous outputs
if exist *.obj del /q *.obj
if exist *.res del /q *.res
if exist dxgi.dll del /q dxgi.dll
if exist dxgi.exp del /q dxgi.exp
if exist dxgi.lib del /q dxgi.lib

set MH_DIR=minhook
if not exist "%MH_DIR%\include\MinHook.h" (
    echo [build] MinHook source missing under %MH_DIR%\ - run: git clone https://github.com/TsudaKageyu/minhook.git %MH_DIR%
    popd
    exit /b 1
)

rem qm_version.h is generated fresh each build from the configurator csproj -
rem the single source of truth for the Quartermaster version. It feeds the PE
rem version resource (version.rc) and the ModTab {version} text token.
set VERSION_CSPROJ=..\..\..\GUI\Web\Quartermaster.Web.csproj
echo [build] generate qm_version.h from GUI\Web\Quartermaster.Web.csproj ...
powershell -NoProfile -Command "$m = Select-String -LiteralPath '%VERSION_CSPROJ%' -Pattern '<Version>([^<]+)</Version>' | Select-Object -First 1; if (-not $m) { exit 1 }; $v = $m.Matches[0].Groups[1].Value.Trim(); $c = ((($v -split '\.') + @('0','0','0','0'))[0..3] -join ','); $q = [char]34; Set-Content -Encoding ascii -LiteralPath 'qm_version.h' -Value @('#ifndef QM_VERSION_H', '#define QM_VERSION_H', ('#define QM_VERSION_STR ' + $q + $v + $q), ('#define QM_VERSION_COMMA ' + $c), '#endif')"
if errorlevel 1 ( echo [build] version extraction failed - is ^<Version^> set in %VERSION_CSPROJ%? & popd & exit /b 1 )

rem qm_modtab_layout_default.h is generated fresh each build from the repo
rem qm_modtab_layout.json - the BASE panel layout is baked into the DLL, so the
rem two can never drift. Files in the game's sidecar folder only EXTEND the
rem layout (qm_modtab_layout_*.json via the "userLayout" row), never replace it.
echo [build] generate qm_modtab_layout_default.h from qm_modtab_layout.json ...
powershell -NoProfile -Command "if (-not (Test-Path 'qm_modtab_layout.json')) { exit 1 }; $j = Get-Content -Raw -LiteralPath 'qm_modtab_layout.json'; if (-not $j -or $j.Trim().Length -eq 0) { exit 1 }; if ($j.Contains(')QMLAYOUT')) { exit 1 }; $q = [char]34; $nl = [char]10; $h = '#ifndef QM_MODTAB_LAYOUT_DEFAULT_H' + $nl + '#define QM_MODTAB_LAYOUT_DEFAULT_H' + $nl + '// GENERATED by build.bat from qm_modtab_layout.json - do not edit, edit the json.' + $nl + 'static constexpr const char* kDefaultLayoutJson = R' + $q + 'QMLAYOUT(' + $j + ')QMLAYOUT' + $q + ';' + $nl + '#endif' + $nl; [IO.File]::WriteAllText((Join-Path (Get-Location) 'qm_modtab_layout_default.h'), $h, (New-Object System.Text.UTF8Encoding($false)))"
if errorlevel 1 ( echo [build] layout header generation failed - check qm_modtab_layout.json exists and contains no QMLAYOUT delimiter & popd & exit /b 1 )

set CONFIG_DEFINE=
set CONFIG_LABEL=dev
if /I "%~1"=="release" (
    set CONFIG_DEFINE=/DQM_BUILD_PRODUCTION
    set CONFIG_LABEL=production
)

set COMMON_FLAGS=/nologo /c /O2 /MT /W3 /DWIN32_LEAN_AND_MEAN /I"%MH_DIR%\include" %CONFIG_DEFINE%

echo [build] config: %CONFIG_LABEL%
echo [build] cl /c Quartermaster C++ sources ...
cl %COMMON_FLAGS% /EHa main.cpp passthrough.cpp qm_log.cpp qm_ue.cpp qm_scan.cpp qm_alloc.cpp qm_crash.cpp qm_config.cpp qm_inject.cpp qm_diag.cpp qm_hook.cpp qm_weather.cpp qm_killxp.cpp qm_shanty.cpp qm_itemgrant.cpp qm_modtab.cpp qm_modtab_util.cpp qm_modtab_widgets.cpp qm_modtab_layout.cpp qm_modtab_inject.cpp qm_modtab_recon.cpp
if errorlevel 1 ( echo [build] cl C++ sources failed. & popd & exit /b 1 )

echo [build] ml64 /c passthrough_asm.asm ...
ml64 /nologo /c passthrough_asm.asm
if errorlevel 1 ( echo [build] ml64 failed. & popd & exit /b 1 )

echo [build] rc version.rc ...
rc /nologo /fo version.res version.rc
if errorlevel 1 ( echo [build] rc failed. & popd & exit /b 1 )

echo [build] cl /c MinHook sources ...
cl %COMMON_FLAGS% "%MH_DIR%\src\buffer.c" "%MH_DIR%\src\hook.c" "%MH_DIR%\src\trampoline.c" "%MH_DIR%\src\hde\hde64.c"
if errorlevel 1 ( echo [build] cl minhook failed. & popd & exit /b 1 )

echo [build] link /DLL ...
link /nologo /DLL /MACHINE:X64 /OUT:dxgi.dll /DEF:passthrough.def ^
    main.obj passthrough.obj passthrough_asm.obj ^
    qm_log.obj qm_ue.obj qm_scan.obj qm_alloc.obj qm_crash.obj qm_config.obj qm_inject.obj qm_diag.obj qm_hook.obj qm_weather.obj qm_killxp.obj qm_shanty.obj qm_itemgrant.obj ^
    qm_modtab.obj qm_modtab_util.obj qm_modtab_widgets.obj qm_modtab_layout.obj qm_modtab_inject.obj qm_modtab_recon.obj ^
    buffer.obj hook.obj trampoline.obj hde64.obj version.res ^
    kernel32.lib user32.lib shell32.lib ole32.lib advapi32.lib
if errorlevel 1 ( echo [build] link failed. & popd & exit /b 1 )

echo.
echo [build] Success (%CONFIG_LABEL%): %SCRIPT_DIR%dxgi.dll
dir dxgi.dll | findstr dxgi.dll

popd
endlocal
